[package]
name = "advent_of_code_2025"
version = "0.1.0"
authors = ["Andrea Princic <andreapri.99@gmail.com>"]
edition = "2021"

[lib]
name = "advent_of_code_2025"
path = "lib.rs"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
utils = { path = "../utils" }
union-find = "0.4.3"