[package]
name = "advent_of_code_2023"
version = "0.1.0"
authors = ["Andrea Princic <andreapri.99@gmail.com>"]
edition = "2021"

[lib]
name = "advent_of_code_2023"
path = "lib.rs"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
utils = { path = "../utils" }
rayon = "1.8.0"
