[package]
name = "advent_of_code_2017"
version = "0.1.0"
authors = ["Andrea Princic <andreapri.99@gmail.com>"]
edition = "2021"

[lib]
name = "advent_of_code_2017"
path = "lib.rs"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
