[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Andrea Princic <andreapri.99@gmail.com>"]
edition = "2021"

[lib]
name = "advent_of_code_2019"
path = "lib.rs"

[[bin]]
name = "main"
path = "main.rs"

[dependencies]
itertools = "0.10.5"
regex = "1.7.2"
rayon = "1.7.0"